### ISSUE TITLE
Broken dependency hnix-0.7.1

### ISSUE THREAD

**Issue by CohenCyril** [timbertson/nix-wrangle#2]
```
$ nix-build --expr 'import (builtins.fetchTarball "https://github.com/timbertson/nix-wrangle/archive/v1.tar.gz")'
unpacking 'https://github.com/timbertson/nix-wrangle/archive/v1.tar.gz'...
trace: [wrangle] Importing derivation self (git-local) from /nix/store/fxidvsk318lm9vrqkknxyqklalgsmays-j3581p4d1f58x2bbz8vx4s5advxa0xix-source/default.nix
error: Package ‘hnix-0.7.1’ in /nix/store/81swl6f42y2p5bsxsmlrkir5khbnr8zi-nixpkgs-20.09pre221814.10100a97c89/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:124194 is marked as broken, refusing to evaluate.
```

**Comment by keidrych** [comment]
This is due to hnix-0.7.1 in nixpkgs as a temporary work-around the following command can be used (pins against an older hnix)
`nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/09b9f22e3ad84ee813cdf7b26fd30bdda94dffde.tar.gz --expr 'import (builtins.fetchTarball "https://github.com/timbertson/nix-wrangle/archive/v1.tar.gz")'`

**Comment by CohenCyril** [comment]
:+1: I think it would be nice to document against which revision of nixpkgs this should be used.

**Comment by timbertson** [comment]
As of 5e2423a6e63f071f22e7ad887dedc2036a732607 I've stopped depending on `hnix` by default, you need to opt in to have the `splice` subcommand available. I'm a bit disappointed that it's been unbuildable in nixpkgs for so long. A fix is on the way, but not sure how long it'll take to propagate.
